name: environment
channels:
  - conda-forge
dependencies:
  - python=3.7
  - sphinx
  - sphinx_rtd_theme
  - sphinx-panels
  - sphinx-tabs
  - sphinx-copybutton
  - sphinx-gallery=0.10.1
  - ipython
  - ipykernel
  - ipympl
  - pip
  - pip:
    - rtcat_sphinx_theme
    - sphinxcontrib-contentui
    - nbsphinx

